### ISSUE TITLE
Django's ManifestStaticFilesStorage incompatible with django-ckeditor

### ISSUE THREAD

**Issue by macolo** [django-ckeditor/django-ckeditor#346]
Even though 5.2.0's changelog states that there was a fix, this doesnt yet work for me.

The only viable solution is to hard code the usage of the original js files that are also collected by `collectstatic` even with `ManifestStaticFilesStorage`.

The failing piece of code sits in ckeditor and is not likely to start working when ckeditor is loaded through another filename than `ckeditor.js`.

**Comment by matthiask** [comment]
The workaround for now is putting the following code at `.../templates/admin/base_site.html`:

```
{% extends "admin/base_site.html" %}

{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
```

I'm still thinking about a better way, but for now that works.

**Comment by peterfarrell** [comment]
+1 on this -- we were using whitenoise to serve files and it broke the paths to .css / .js that ckeditor includes.

**Comment by riklaunim** [comment]
Should work now

**Comment by Flimm** [comment]
Unfortunately, it still doesn't work, due to the issue I mentioned in the pull request #377 .
